# preprocessing:
#   method: StandardScaler
#   params: 
#     copy: true
#     with_mean: true
#     with_std: true

# decomposition:
#   method: SelectKBest
#   params: 
#     k: 10
#     score_func: f_classif # f_classif, f_regression, mutual_info_classif, mutual_info_regression

preprocessing:
  method: Pipeline
  params:
    steps:
      # - name: "combat"
      #   method: "hiomics.preprocessing.pycombat_wrapper.ComBatTransformer"
      #   params:
      #     parametric: true
      #     mean_only: false
      - name: "imputer"
        method: "sklearn.impute.SimpleImputer"
        params:
          strategy: "mean"
      - name: "scaler"
        method: "sklearn.preprocessing.StandardScaler"
        params:
          copy: true
          with_mean: true
          with_std: true
      - name: "variance_selector"
        method: "sklearn.feature_selection.VarianceThreshold"
        params:
          threshold: 0.05
      # - name: "pca_reducer"
      #   method: "sklearn.decomposition.PCA"
      #   params:
      #     n_components: 0.95
      #     random_state: 42

cluster:
  method: GaussianMixture
  params: 
    covariance_type: full
    max_iter: 1000
    random_state: 42

    n_clusters: null
    n_clusters_range: [2, 5]
    n_clusters_score_method: BIC